name: Postman API Tests
on:
  push:
    branches: [ sm-dev ]
  pull_request:
    branches: [ main ]

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "45236363-e707068e-ba6a-49f6-8050-0e03bb9a1e42"